good upload

diff --git a/.buildkite/hooks/post-command b/.buildkite/hooks/post-command
--- a/.buildkite/hooks/post-command
+++ b/.buildkite/hooks/post-command
@@ -3,11 +3,15 @@ set -euo pipefail
 
 echo "Post-artifact hook, searching for artifact"
 
-output=$(buildkite-agent artifact search testr/revisions1/foo.txt 2>&1)
-status=$?
-if [ $status -eq 0 ]; then
-  echo "Artifact found"
-else
-  echo "Artifact not found or an error occurred"
-  echo "Error details: $output"
+
+if [BUILDKITE_LABEL=":test multi line:"]then
+    echo "searching for artifact"
+    output=$(buildkite-agent artifact search testr/revisions1/foo.txt 2>&1)
+    status=$?
+    if [ $status -eq 0 ]; then
+        echo "Artifact found"
+    else
+        echo "Artifact not found or an error occurred"
+        echo "Error details: $output"
+    fi
 fi
